/// <reference path="../pb_data/types.d.ts" />
const collections = [
  {
    "id": "c_ticketsxxxxxx",
    "name": "tickets",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_transporttype",
        "name": "transportType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_transportlabe",
        "name": "transportLabel",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_basedurationx",
        "name": "baseDuration",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_basepricexxxx",
        "name": "basePrice",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_usableminutes",
        "name": "usableMinutes",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_pricexxxxxxxx",
        "name": "price",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ratingscorexx",
        "name": "ratingScore",
        "type": "number",
        "min": -5,
        "max": 5,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ratinggradex",
        "name": "ratingGrade",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ratingtypexx",
        "name": "ratingType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "generated",
          "shop_available",
          "auction_available",
          "owned",
          "reserved",
          "consumed",
          "destroyed"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketsourcex",
        "name": "ticketSource",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ownerplayerid",
        "name": "ownerPlayerId",
        "type": "relation",
        "collectionId": "c_playersxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ownergameplay",
        "name": "ownerGamePlayerId",
        "type": "relation",
        "collectionId": "c_game_playersx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_sourceauction",
        "name": "sourceAuctionId",
        "type": "relation",
        "collectionId": "c_auctionsxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_sourcejourney",
        "name": "sourceJourneyId",
        "type": "relation",
        "collectionId": "c_journeysxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_metadataxxxxx",
        "name": "metadata",
        "type": "json",
        "maxSize": 0
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_acquiredatxxx",
        "name": "acquiredAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_consumedatxxx",
        "name": "consumedAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyedatxx",
        "name": "destroyedAt",
        "type": "date",
        "min": "",
        "max": ""
      }
    ],
    "indexes": [
      "CREATE INDEX idx_tickets_game_status ON tickets (gameId, status)",
      "CREATE INDEX idx_tickets_owner ON tickets (ownerPlayerId, status)"
    ]
  },
  {
    "id": "c_shopsxxxxxxxx",
    "name": "shops",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_mapidxxxxxxxx",
        "name": "mapId",
        "type": "relation",
        "collectionId": "c_mapsxxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_shoptypexxxxx",
        "name": "shopType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "open",
          "closed"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastrefreshat",
        "name": "lastRefreshAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastrefreshty",
        "name": "lastRefreshType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastdailyfree",
        "name": "lastDailyFreeRefreshAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_prioritybuyer",
        "name": "priorityBuyerPlayerId",
        "type": "relation",
        "collectionId": "c_playersxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_prioritystart",
        "name": "priorityStartedAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_priorityendsx",
        "name": "priorityEndsAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_prioritysour",
        "name": "prioritySource",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX idx_shops_game_type ON shops (gameId, shopType)"
    ]
  },
  {
    "id": "c_auctionsxxxxx",
    "name": "auctions",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_mapidxxxxxxxx",
        "name": "mapId",
        "type": "relation",
        "collectionId": "c_mapsxxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_shoptypexxxxx",
        "name": "shopType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketidxxxxx",
        "name": "ticketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "scheduled",
          "active",
          "ended",
          "resolved",
          "destroyed",
          "meta"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_starttimexxxx",
        "name": "startTime",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_endtimexxxxxx",
        "name": "endTime",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_winnerplayeri",
        "name": "winnerPlayerId",
        "type": "relation",
        "collectionId": "c_playersxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_awardedticket",
        "name": "awardedTicketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyedtick",
        "name": "destroyedTicketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketrscore",
        "name": "ticketRatingScore",
        "type": "number",
        "min": -5,
        "max": 5,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketrgrade",
        "name": "ticketRatingGrade",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketrtypex",
        "name": "ticketRatingType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_bidcountxxxxx",
        "name": "bidCount",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_totalbidamoun",
        "name": "totalBidAmount",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_resolvedatxxx",
        "name": "resolvedAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyreason",
        "name": "destroyReason",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastresolveda",
        "name": "lastResolvedAuctionId",
        "type": "relation",
        "collectionId": "c_auctionsxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      }
    ],
    "indexes": [
      "CREATE INDEX idx_auctions_game_status ON auctions (gameId, status)",
      "CREATE INDEX idx_auctions_time ON auctions (gameId, startTime, endTime)"
    ]
  }
];

const rollbackCollections = [
  {
    "id": "c_ticketsxxxxxx",
    "name": "tickets",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_transporttype",
        "name": "transportType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_transportlabe",
        "name": "transportLabel",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_usableminutes",
        "name": "usableMinutes",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_pricexxxxxxxx",
        "name": "price",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "generated",
          "shop_available",
          "auction_available",
          "owned",
          "reserved",
          "consumed",
          "destroyed"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketsourcex",
        "name": "ticketSource",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ownerplayerid",
        "name": "ownerPlayerId",
        "type": "relation",
        "collectionId": "c_playersxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ownergameplay",
        "name": "ownerGamePlayerId",
        "type": "relation",
        "collectionId": "c_game_playersx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_sourceauction",
        "name": "sourceAuctionId",
        "type": "relation",
        "collectionId": "c_auctionsxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_sourcejourney",
        "name": "sourceJourneyId",
        "type": "relation",
        "collectionId": "c_journeysxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_metadataxxxxx",
        "name": "metadata",
        "type": "json",
        "maxSize": 0
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_acquiredatxxx",
        "name": "acquiredAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_consumedatxxx",
        "name": "consumedAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyedatxx",
        "name": "destroyedAt",
        "type": "date",
        "min": "",
        "max": ""
      }
    ],
    "indexes": [
      "CREATE INDEX idx_tickets_game_status ON tickets (gameId, status)",
      "CREATE INDEX idx_tickets_owner ON tickets (ownerPlayerId, status)"
    ]
  },
  {
    "id": "c_shopsxxxxxxxx",
    "name": "shops",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_mapidxxxxxxxx",
        "name": "mapId",
        "type": "relation",
        "collectionId": "c_mapsxxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": true,
        "system": false,
        "id": "f_shoptypexxxxx",
        "name": "shopType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "open",
          "closed"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastrefreshat",
        "name": "lastRefreshAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastrefreshty",
        "name": "lastRefreshType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastdailyfree",
        "name": "lastDailyFreeRefreshAt",
        "type": "date",
        "min": "",
        "max": ""
      }
    ],
    "indexes": [
      "CREATE UNIQUE INDEX idx_shops_game_type ON shops (gameId, shopType)"
    ]
  },
  {
    "id": "c_auctionsxxxxx",
    "name": "auctions",
    "type": "base",
    "system": false,
    "listRule": null,
    "viewRule": null,
    "createRule": null,
    "updateRule": null,
    "deleteRule": null,
    "fields": [
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_gameidxxxxxxx",
        "name": "gameId",
        "type": "relation",
        "collectionId": "c_gamesxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_mapidxxxxxxxx",
        "name": "mapId",
        "type": "relation",
        "collectionId": "c_mapsxxxxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_shoptypexxxxx",
        "name": "shopType",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_ticketidxxxxx",
        "name": "ticketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_statusxxxxxxx",
        "name": "status",
        "type": "select",
        "maxSelect": 1,
        "values": [
          "scheduled",
          "active",
          "ended",
          "resolved",
          "destroyed",
          "meta"
        ]
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_starttimexxxx",
        "name": "startTime",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_endtimexxxxxx",
        "name": "endTime",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_winnerplayeri",
        "name": "winnerPlayerId",
        "type": "relation",
        "collectionId": "c_playersxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_awardedticket",
        "name": "awardedTicketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyedtick",
        "name": "destroyedTicketId",
        "type": "relation",
        "collectionId": "c_ticketsxxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_bidcountxxxxx",
        "name": "bidCount",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_totalbidamoun",
        "name": "totalBidAmount",
        "type": "number",
        "min": 0,
        "max": null,
        "onlyInt": false
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_resolvedatxxx",
        "name": "resolvedAt",
        "type": "date",
        "min": "",
        "max": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_destroyreason",
        "name": "destroyReason",
        "type": "text",
        "min": 0,
        "max": 0,
        "pattern": ""
      },
      {
        "hidden": false,
        "presentable": false,
        "required": false,
        "system": false,
        "id": "f_lastresolveda",
        "name": "lastResolvedAuctionId",
        "type": "relation",
        "collectionId": "c_auctionsxxxxx",
        "cascadeDelete": false,
        "minSelect": null,
        "maxSelect": 1
      }
    ],
    "indexes": [
      "CREATE INDEX idx_auctions_game_status ON auctions (gameId, status)",
      "CREATE INDEX idx_auctions_time ON auctions (gameId, startTime, endTime)"
    ]
  }
];

migrate((app) => {
  app.importCollections(collections, false)
}, (app) => {
  app.importCollections(rollbackCollections, false)
})
