const text = (name, options = {}) => ({ name, type: "text", ...options });
const number = (name, options = {}) => ({ name, type: "number", ...options });
const bool = (name, options = {}) => ({ name, type: "bool", ...options });
const json = (name, options = {}) => ({ name, type: "json", ...options });
const date = (name, options = {}) => ({ name, type: "date", ...options });
const select = (name, values, options = {}) => ({
  name,
  type: "select",
  values,
  ...options,
});
const relation = (name, collection, options = {}) => ({
  name,
  type: "relation",
  collection,
  ...options,
});

export const coreCollectionsDraft = [
  {
    name: "maps",
    purpose: "Map definitions and map-level transport settings.",
    fields: [
      text("name", { required: true }),
      text("description"),
      text("countryOrRegion"),
      json("availableTransportTypes", { required: true }),
      json("customRules"),
      relation("startLocation", "locations", { maxSelect: 1 }),
      relation("goalLocation", "locations", { maxSelect: 1 }),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_maps_name ON maps (name)",
    ],
  },
  {
    name: "locations",
    purpose: "Locations that belong to a map.",
    fields: [
      relation("mapId", "maps", { required: true, maxSelect: 1 }),
      text("name", { required: true }),
      text("locationType"),
      json("metadata"),
    ],
    indexes: [
      "CREATE INDEX idx_locations_map ON locations (mapId)",
      "CREATE UNIQUE INDEX idx_locations_map_name ON locations (mapId, name)",
    ],
  },
  {
    name: "players",
    purpose: "Cross-game player profile data.",
    fields: [
      text("userId", { required: true }),
      text("authUserId"),
      text("displayName", { required: true }),
      text("avatar"),
      json("metadata"),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_players_user_id ON players (userId)",
      "CREATE UNIQUE INDEX idx_players_auth_user_id ON players (authUserId) WHERE authUserId IS NOT NULL AND authUserId != ''",
    ],
  },
  {
    name: "games",
    purpose: "A game room and its global runtime state.",
    fields: [
      text("name"),
      relation("mapId", "maps", { required: true, maxSelect: 1 }),
      relation("hostPlayerId", "players", { required: true, maxSelect: 1 }),
      relation("startLocationId", "locations", { required: true, maxSelect: 1 }),
      relation("goalLocationId", "locations", { required: true, maxSelect: 1 }),
      select("status", ["waiting", "started", "ended"], { required: true }),
      number("initialMoney", { required: true, min: 0 }),
      date("plannedStartTime"),
      date("startedAt"),
      date("endedAt"),
      json("gameSettings"),
      json("blindBoxSettings"),
    ],
    indexes: [
      "CREATE INDEX idx_games_status ON games (status)",
      "CREATE INDEX idx_games_map ON games (mapId)",
    ],
  },
  {
    name: "game_players",
    purpose: "Per-game player runtime state.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      select("status", ["waiting", "active", "arrived", "offline"], { required: true }),
      number("money", { required: true, min: 0 }),
      relation("currentLocationId", "locations", { maxSelect: 1 }),
      relation("currentJourneyId", "journeys", { maxSelect: 1 }),
      relation("reservedJourneyId", "journeys", { maxSelect: 1 }),
      date("arrivedAt"),
      number("freeShopRefreshCount", { min: 0 }),
      bool("hasNextAuctionBidPoolReward"),
      json("privateState"),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_game_players_game_player ON game_players (gameId, playerId)",
      "CREATE INDEX idx_game_players_status ON game_players (gameId, status)",
    ],
  },
  {
    name: "tickets",
    purpose: "Ticket master records no matter where they currently live.",
    fields: [
      relation("gameId", "games", { maxSelect: 1 }),
      text("transportType", { required: true }),
      text("transportLabel"),
      number("baseDuration", { min: 0 }),
      number("basePrice", { min: 0 }),
      number("usableMinutes", { required: true, min: 0 }),
      number("price", { min: 0 }),
      number("ratingScore", { min: -5, max: 5 }),
      text("ratingGrade"),
      text("ratingType"),
      select("status", [
        "generated",
        "shop_available",
        "auction_available",
        "owned",
        "reserved",
        "consumed",
        "destroyed",
      ], { required: true }),
      text("ticketSource"),
      relation("ownerPlayerId", "players", { maxSelect: 1 }),
      relation("ownerGamePlayerId", "game_players", { maxSelect: 1 }),
      relation("sourceAuctionId", "auctions", { maxSelect: 1 }),
      relation("sourceJourneyId", "journeys", { maxSelect: 1 }),
      json("metadata"),
      date("acquiredAt"),
      date("consumedAt"),
      date("destroyedAt"),
    ],
    indexes: [
      "CREATE INDEX idx_tickets_game_status ON tickets (gameId, status)",
      "CREATE INDEX idx_tickets_owner ON tickets (ownerPlayerId, status)",
    ],
  },
  {
    name: "player_tickets",
    purpose: "Ownership relation between a player in a game and a ticket.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      relation("gamePlayerId", "game_players", { maxSelect: 1 }),
      relation("ticketId", "tickets", { required: true, maxSelect: 1 }),
      text("source"),
      date("createdAt"),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_player_tickets_unique ON player_tickets (gameId, playerId, ticketId)",
      "CREATE INDEX idx_player_tickets_ticket ON player_tickets (ticketId)",
    ],
  },
  {
    name: "journeys",
    purpose: "Planned and active journeys.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      relation("gamePlayerId", "game_players", { maxSelect: 1 }),
      relation("fromLocationId", "locations", { required: true, maxSelect: 1 }),
      relation("toLocationId", "locations", { required: true, maxSelect: 1 }),
      text("transportType", { required: true }),
      json("ticketIdList"),
      select("status", [
        "reserved",
        "started",
        "completed",
        "cancelled",
        "incident_pending",
        "incident_resolved",
      ], { required: true }),
      date("departureTime", { required: true }),
      date("arrivalTime", { required: true }),
      date("startedAt"),
      date("completedAt"),
      bool("isLocked"),
      json("metadata"),
    ],
    indexes: [
      "CREATE INDEX idx_journeys_game_player_status ON journeys (gameId, playerId, status)",
      "CREATE INDEX idx_journeys_departure ON journeys (gameId, departureTime)",
    ],
  },
  {
    name: "shops",
    purpose: "General shop runtime state.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("mapId", "maps", { required: true, maxSelect: 1 }),
      text("shopType", { required: true }),
      select("status", ["open", "closed"], { required: true }),
      date("lastRefreshAt"),
      text("lastRefreshType"),
      date("lastDailyFreeRefreshAt"),
      relation("priorityBuyerPlayerId", "players", { maxSelect: 1 }),
      date("priorityStartedAt"),
      date("priorityEndsAt"),
      text("prioritySource"),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_shops_game_type ON shops (gameId, shopType)",
    ],
  },
  {
    name: "shop_items",
    purpose: "Tickets currently or previously listed in the general shop.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("mapId", "maps", { required: true, maxSelect: 1 }),
      text("shopType", { required: true }),
      relation("ticketId", "tickets", { required: true, maxSelect: 1 }),
      number("price", { min: 0 }),
      text("status", { required: true }),
      relation("purchasedBy", "players", { maxSelect: 1 }),
      date("listedAt"),
      date("purchasedAt"),
      date("removedAt"),
      text("removedReason"),
    ],
    indexes: [
      "CREATE INDEX idx_shop_items_game_status ON shop_items (gameId, status)",
      "CREATE INDEX idx_shop_items_ticket ON shop_items (ticketId)",
    ],
  },
  {
    name: "auctions",
    purpose: "Auction rounds and auction meta state.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("mapId", "maps", { maxSelect: 1 }),
      text("shopType"),
      relation("ticketId", "tickets", { maxSelect: 1 }),
      select("status", ["scheduled", "active", "ended", "resolved", "destroyed", "meta"], { required: true }),
      date("startTime"),
      date("endTime"),
      relation("winnerPlayerId", "players", { maxSelect: 1 }),
      relation("awardedTicketId", "tickets", { maxSelect: 1 }),
      relation("destroyedTicketId", "tickets", { maxSelect: 1 }),
      number("ticketRatingScore", { min: -5, max: 5 }),
      text("ticketRatingGrade"),
      text("ticketRatingType"),
      number("bidCount", { min: 0 }),
      number("totalBidAmount", { min: 0 }),
      date("resolvedAt"),
      text("destroyReason"),
      relation("lastResolvedAuctionId", "auctions", { maxSelect: 1 }),
    ],
    indexes: [
      "CREATE INDEX idx_auctions_game_status ON auctions (gameId, status)",
      "CREATE INDEX idx_auctions_time ON auctions (gameId, startTime, endTime)",
    ],
  },
  {
    name: "auction_bids",
    purpose: "All auction bids; bids are never refunded.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("auctionId", "auctions", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      relation("gamePlayerId", "game_players", { maxSelect: 1 }),
      number("bidAmount", { required: true, min: 0 }),
      date("createdAt"),
    ],
    indexes: [
      "CREATE UNIQUE INDEX idx_auction_bids_unique ON auction_bids (auctionId, playerId)",
      "CREATE INDEX idx_auction_bids_amount ON auction_bids (auctionId, bidAmount)",
    ],
  },
  {
    name: "blind_boxes",
    purpose: "Blind box placement, visibility and open state.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("locationId", "locations", { required: true, maxSelect: 1 }),
      select("status", ["hidden_effect", "available", "opened", "removed"], { required: true }),
      json("effectData", { required: true }),
      bool("openedStatus"),
      relation("openedBy", "players", { maxSelect: 1 }),
      date("openedAt"),
      relation("createdBy", "players", { maxSelect: 1 }),
      date("removedAt"),
    ],
    indexes: [
      "CREATE INDEX idx_blind_boxes_game_status ON blind_boxes (gameId, status)",
      "CREATE INDEX idx_blind_boxes_location ON blind_boxes (gameId, locationId)",
    ],
  },
  {
    name: "blind_box_effect_logs",
    purpose: "Blind box actions and effect execution logs.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("blindBoxId", "blind_boxes", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { maxSelect: 1 }),
      text("actionType", { required: true }),
      json("actionData"),
      date("createdAt"),
    ],
    indexes: [
      "CREATE INDEX idx_blind_box_logs_box_time ON blind_box_effect_logs (blindBoxId, createdAt)",
      "CREATE INDEX idx_blind_box_logs_player ON blind_box_effect_logs (playerId)",
    ],
  },
  {
    name: "player_special_states",
    purpose: "Delayed blind box effects such as free refresh count or next auction reward.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      relation("gamePlayerId", "game_players", { maxSelect: 1 }),
      text("stateType", { required: true }),
      json("stateData"),
      relation("sourceBlindBoxId", "blind_boxes", { maxSelect: 1 }),
      bool("isConsumed"),
      date("consumedAt"),
      text("consumeReason"),
      date("createdAt"),
    ],
    indexes: [
      "CREATE INDEX idx_special_states_active ON player_special_states (gameId, playerId, stateType, isConsumed)",
    ],
  },
  {
    name: "traffic_incident_requests",
    purpose: "Requests for partial journey refunds after service interruption.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { required: true, maxSelect: 1 }),
      relation("journeyId", "journeys", { required: true, maxSelect: 1 }),
      text("status", { required: true }),
      relation("actualEndLocationId", "locations", { maxSelect: 1 }),
      date("actualEndedAt"),
      json("evidenceList"),
      text("description"),
      json("reviewData"),
      date("createdAt"),
      date("resolvedAt"),
    ],
    indexes: [
      "CREATE INDEX idx_incidents_game_status ON traffic_incident_requests (gameId, status)",
      "CREATE INDEX idx_incidents_journey ON traffic_incident_requests (journeyId)",
    ],
  },
  {
    name: "records",
    purpose: "Generic audit trail for all gameplay actions.",
    fields: [
      relation("gameId", "games", { required: true, maxSelect: 1 }),
      relation("playerId", "players", { maxSelect: 1 }),
      text("recordType", { required: true }),
      text("action", { required: true }),
      json("payload"),
      date("createdAt", { required: true }),
    ],
    indexes: [
      "CREATE INDEX idx_records_game_time ON records (gameId, createdAt)",
      "CREATE INDEX idx_records_player_time ON records (playerId, createdAt)",
    ],
  },
];

export default coreCollectionsDraft;
