export const CollectionName = Object.freeze({
  MAPS: "maps",
  LOCATIONS: "locations",
  GAMES: "games",
  GAME_PLAYERS: "game_players",
  PLAYERS: "players",
  TICKETS: "tickets",
  PLAYER_TICKETS: "player_tickets",
  JOURNEYS: "journeys",
  SHOPS: "shops",
  SHOP_ITEMS: "shop_items",
  AUCTIONS: "auctions",
  AUCTION_BIDS: "auction_bids",
  BLIND_BOXES: "blind_boxes",
  BLIND_BOX_EFFECT_LOGS: "blind_box_effect_logs",
  PLAYER_SPECIAL_STATES: "player_special_states",
  TRAFFIC_INCIDENT_REQUESTS: "traffic_incident_requests",
  RECORDS: "records",
});
